In [1]:
import numpy as np

In [2]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])

In [3]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = np.mean(a, axis=0)

In [5]:
mean_a

array([2. , 8.4])

In [9]:
a_centered = a - mean_a

In [10]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [49]:
a_transp = a_centered.T

In [50]:
a_centered_sp = np.dot(a_transp[0], a_transp[1])

In [51]:
a_centered_sp

8.0

In [52]:
a_centered_sp / 4

2.0

In [53]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])